FROM python:3.9.14-buster
WORKDIR /root
COPY ["./ae/config", "/root/.ssh/config"]
COPY ["./ae/id_rsa", "/root/.ssh/id_rsa"]
RUN apt-get update &&\ 
    apt-get install -y --no-install-recommends bc &&\
    mkdir logging &&\
    chmod 400 /root/.ssh/id_rsa &&\
    pip3 install numpy matplotlib
COPY ["./plot*.sh", "./"]
COPY ["./run*.sh", "./"]
COPY ["./run.py", "./run.py"]
CMD tail -f /dev/null